### ISSUE TITLE
UnitOfWork implementation

### ISSUE THREAD

**Issue by VisualBean** [zkavtaskin/Domain-Driven-Design-Example#3]
How would the UnitOfWork be implemented in this project?
More specifically;  
In the `CustomerService.Update` method it ends with
```
customer.ChangeEmail(customerDto.Email);
this.unitOfWork.Commit();
```
But I dont see any implementation which actually makes this work.  
The MemoryUnitOfWork contains nothing but comments.
Maybe i'm missing something?

**Comment by zkavtaskin** [comment]
Hello,

A while back I have written this blog post about the unit of work:
http://www.zankavtaskin.com/2013/12/unit-of-work-for-nhibernate-and-entity.html

If you would like to see the actual implementation then I suggest you check out my other latest project:
https://github.com/zkavtaskin/Multitenancy-Microservice-FederatedIdentity-Example/blob/master/Server/Core/Repository/Adapters/NHibernate/NHUnitOfWork.cs

I hope this helps!
