### ISSUE TITLE
Can't start webservice

### ISSUE THREAD

**Issue by xXTraceXx** [zkavtaskin/Domain-Driven-Design-Example#6]
Hello,

i want to start your application for learning purposes, but if i try to start the eCommerce.WebService i get the following error:

Server Error in the Application /.

Resource can not be found.

Description: HTTP 404. The resource you are looking for or one of its dependencies may have been removed, renamed, or temporarily unavailable. Check the following URL and make sure it is spelled correctly.
Requested URL: /

How i resolve this? Thank you in advance!

**Comment by zkavtaskin** [comment]
Thank you for letting me know, I will check this out over the next week.

**Comment by zkavtaskin** [comment]
Hello, this is default behaviour, once you start the "eCommerce.WebService" project, your browser should open localhost:xxxx. Once this happens please follow examples here: https://github.com/zkavtaskin/Domain-Driven-Design-Example/blob/master/README.md so add /api/customer/Getbyid/5D5020DA-47DF-4C82-A722-C8DEAF06AE23 to your localhost:xxxx i.e. localhost:xxxx/api/customer/Getbyid/5D5020DA-47DF-4C82-A722-C8DEAF06AE23. Once you start doing this you get back XML API response. 

Please let me know if this resolves your issue.

**Comment by xXTraceXx** [comment]
@zkavtaskin it worked. I thought this example project has an UI^^. Thank you for your advice!
